// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyHub.Persistence;

#nullable disable

namespace StudyHub.Persistence.Migrations
{
    [DbContext(typeof(StudyHubDbContext))]
    [Migration("20260701183556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyHub.Domain.Entities.CauHinhHeThong", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCauHinh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaCauHinh");

                    b.ToTable("CauHinhHeThong", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.CongViec", b =>
                {
                    b.Property<int>("MaCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongViec"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<bool>("DanhDauQuanTrong")
                        .HasColumnType("bit");

                    b.Property<bool>("DanhDauYeuThich")
                        .HasColumnType("bit");

                    b.Property<byte>("DoUuTien")
                        .HasColumnType("tinyint");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LapLai")
                        .HasColumnType("bit");

                    b.Property<int?>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhomCongViec")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanLap")
                        .HasColumnType("int");

                    b.Property<int>("TiLeHoanThanh")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaCongViec");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhomCongViec");

                    b.ToTable("CongViec", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.FileTaiLen", b =>
                {
                    b.Property<int>("MaFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaFile"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<long>("DungLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLuu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaFile");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("FileTaiLen", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.HoiThoaiAI", b =>
                {
                    b.Property<int>("MaHoiThoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoiThoai"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<byte>("LoaiHoiThoai")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHoiThoai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HoiThoaiAI", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanBoard", b =>
                {
                    b.Property<int>("MaBoard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBoard"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBoard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBoard");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("KanbanBoard", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanCot", b =>
                {
                    b.Property<int>("MaCot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCot"));

                    b.Property<int?>("GioiHanThe")
                        .HasColumnType("int");

                    b.Property<int>("MaBoard")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCot");

                    b.HasIndex("MaBoard");

                    b.ToTable("KanbanCot", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanThe", b =>
                {
                    b.Property<int>("MaThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThe"));

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int>("MaCot")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaThe");

                    b.HasIndex("MaCongViec")
                        .IsUnique();

                    b.HasIndex("MaCot");

                    b.ToTable("KanbanThe", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichHoc", b =>
                {
                    b.Property<int>("MaLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHoc"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GiangVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Thu")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TietBatDau")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TietKetThuc")
                        .HasColumnType("tinyint");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichHoc", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichSuQuiz", b =>
                {
                    b.Property<int>("MaQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuiz"));

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("DiemSo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoCauHoi")
                        .HasColumnType("int");

                    b.HasKey("MaQuiz");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuQuiz", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichSuTomTat", b =>
                {
                    b.Property<int>("MaTomTat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTomTat"));

                    b.Property<int>("MaFile")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTomTat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTomTat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTomTat");

                    b.HasIndex("MaFile");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuTomTat", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichThi", b =>
                {
                    b.Property<int>("MaLichThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichThi"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThucThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaLichThi");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichThi", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LoaiThongBao", b =>
                {
                    b.Property<int>("MaLoaiThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiThongBao"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiThongBao");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("LoaiThongBao", (string)null);

                    b.HasData(
                        new
                        {
                            MaLoaiThongBao = 1,
                            Icon = "bi bi-alarm",
                            MauSac = "text-danger",
                            MoTa = "Thong bao han chot cong viec",
                            TenLoai = "Deadline"
                        },
                        new
                        {
                            MaLoaiThongBao = 2,
                            Icon = "bi bi-bell",
                            MauSac = "text-warning",
                            MoTa = "Nhac nho hoc tap, su kien",
                            TenLoai = "Reminder"
                        },
                        new
                        {
                            MaLoaiThongBao = 3,
                            Icon = "bi bi-people",
                            MauSac = "text-primary",
                            MoTa = "Thong bao hoat dong nhom",
                            TenLoai = "Group"
                        },
                        new
                        {
                            MaLoaiThongBao = 4,
                            Icon = "bi bi-shield-exclamation",
                            MauSac = "text-secondary",
                            MoTa = "Thong bao tu he thong",
                            TenLoai = "System"
                        },
                        new
                        {
                            MaLoaiThongBao = 5,
                            Icon = "bi bi-cpu",
                            MauSac = "text-info",
                            MoTa = "Goi y va bao cao tu AI",
                            TenLoai = "AI"
                        });
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonHoc"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaMonHoc");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            DaXoa = false,
                            Email = "admin@studyhub.com",
                            HoTen = "System Admin",
                            MaVaiTro = 1,
                            MatKhauHash = "AQAAAAIAAYagAAAAEO9gD1yVzH7qKqTjV+UomN+gI6s8D/H8lE3wFvC9W2vVw==",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TrangThai = (byte)1
                        });
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhatKyHeThong", b =>
                {
                    b.Property<long>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLog"));

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("MucDo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrinhDuyet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLog");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhomCongViec", b =>
                {
                    b.Property<int>("MaNhomCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomCongViec"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaNhomCongViec");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhomCongViec", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhomHocTap", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int?>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("MaThamGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaNhom");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaThamGia")
                        .IsUnique();

                    b.ToTable("NhomHocTap", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.PhienDangNhap", b =>
                {
                    b.Property<int>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhien"));

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("ThietBi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGianDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDangXuat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrinhDuyet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaPhien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PhienDangNhap", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.PomodoroSession", b =>
                {
                    b.Property<int>("MaSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSession"));

                    b.Property<byte>("LoaiSession")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaCongViec")
                        .HasColumnType("int");

                    b.Property<int?>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanTamDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TongThoiGianTamDung")
                        .HasColumnType("int");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaSession");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PomodoroSession", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.SuKien", b =>
                {
                    b.Property<int>("MaSuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuKien"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LapLai")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhacTruoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaSuKien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("SuKien", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("LuotTai")
                        .HasColumnType("int");

                    b.Property<int>("MaFile")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiTaiLen")
                        .HasColumnType("int");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex("MaFile");

                    b.HasIndex("MaNguoiTaiLen");

                    b.HasIndex("MaNhom");

                    b.ToTable("TaiLieu", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TepDinhKemTinNhan", b =>
                {
                    b.Property<int>("MaTep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTep"));

                    b.Property<int>("MaFile")
                        .HasColumnType("int");

                    b.Property<int>("MaTinNhan")
                        .HasColumnType("int");

                    b.HasKey("MaTep");

                    b.HasIndex("MaFile");

                    b.HasIndex("MaTinNhan");

                    b.ToTable("TepDinhKemTinNhan", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.ThanhVienNhom", b =>
                {
                    b.Property<int>("MaThanhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhVien"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<byte>("VaiTro")
                        .HasColumnType("tinyint");

                    b.HasKey("MaThanhVien");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhom", "MaNguoiDung")
                        .IsUnique();

                    b.ToTable("ThanhVienNhom", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLoaiThongBao")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<byte>("MucDo")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaLoaiThongBao");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.ThongKeHocTap", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<int>("CongViecHoanThanh")
                        .HasColumnType("int");

                    b.Property<int>("CongViecQuaHan")
                        .HasColumnType("int");

                    b.Property<decimal>("DiemNangSuat")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThongKe")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNgayHocLienTiep")
                        .HasColumnType("int");

                    b.Property<int>("TongCongViec")
                        .HasColumnType("int");

                    b.Property<int>("TongPhutHoc")
                        .HasColumnType("int");

                    b.Property<int>("TongPomodoro")
                        .HasColumnType("int");

                    b.Property<decimal>("TyLeHoanThanh")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MaThongKe");

                    b.HasIndex("MaNguoiDung", "NgayThongKe")
                        .IsUnique();

                    b.ToTable("ThongKeHocTap", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<bool>("DaChinhSua")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<byte>("LoaiTinNhan")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaNguoiGui")
                        .HasColumnType("int");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNhom");

                    b.ToTable("TinNhan", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TinNhanAI", b =>
                {
                    b.Property<int>("MaTinNhanAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhanAI"));

                    b.Property<int>("MaHoiThoai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokenSuDung")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTinNhanAI");

                    b.HasIndex("MaHoiThoai");

                    b.ToTable("TinNhanAI", (string)null);
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            DaXoa = false,
                            MoTa = "Quan tri he thong",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "Administrator"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            DaXoa = false,
                            MoTa = "Sinh vien / Nguoi dung",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenVaiTro = "Student"
                        });
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.CongViec", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("CongViec")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("CongViec")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NhomCongViec", "NhomCongViec")
                        .WithMany("CongViec")
                        .HasForeignKey("MaNhomCongViec")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");

                    b.Navigation("NhomCongViec");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.FileTaiLen", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("FileTaiLen")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.HoiThoaiAI", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("HoiThoaiAI")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanBoard", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("KanbanBoard")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanCot", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.KanbanBoard", "KanbanBoard")
                        .WithMany("KanbanCot")
                        .HasForeignKey("MaBoard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanbanBoard");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanThe", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.CongViec", "CongViec")
                        .WithOne("KanbanThe")
                        .HasForeignKey("StudyHub.Domain.Entities.KanbanThe", "MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.KanbanCot", "KanbanCot")
                        .WithMany("KanbanThe")
                        .HasForeignKey("MaCot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("KanbanCot");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichHoc", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("LichHoc")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichHoc")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichSuQuiz", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichSuQuiz")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichSuTomTat", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.FileTaiLen", "FileTaiLen")
                        .WithMany("LichSuTomTat")
                        .HasForeignKey("MaFile")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichSuTomTat")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileTaiLen");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LichThi", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("LichThi")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichThi")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDung")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhatKyHeThong", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyHeThong")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhomCongViec", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NhomCongViec")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhomHocTap", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("NhomHocTap")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiTao")
                        .WithMany("NhomHocTap")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.PhienDangNhap", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("PhienDangNhap")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.PomodoroSession", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.CongViec", "CongViec")
                        .WithMany("PomodoroSession")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyHub.Domain.Entities.MonHoc", "MonHoc")
                        .WithMany("PomodoroSession")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("PomodoroSession")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.SuKien", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("SuKien")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TaiLieu", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.FileTaiLen", "FileTaiLen")
                        .WithMany("TaiLieu")
                        .HasForeignKey("MaFile")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiTaiLen")
                        .WithMany("TaiLieu")
                        .HasForeignKey("MaNguoiTaiLen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NhomHocTap", "NhomHocTap")
                        .WithMany("TaiLieu")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileTaiLen");

                    b.Navigation("NguoiTaiLen");

                    b.Navigation("NhomHocTap");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TepDinhKemTinNhan", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.FileTaiLen", "FileTaiLen")
                        .WithMany("TepDinhKemTinNhan")
                        .HasForeignKey("MaFile")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.TinNhan", "TinNhan")
                        .WithMany("TepDinhKemTinNhan")
                        .HasForeignKey("MaTinNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileTaiLen");

                    b.Navigation("TinNhan");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.ThanhVienNhom", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("ThanhVienNhom")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NhomHocTap", "NhomHocTap")
                        .WithMany("ThanhVienNhom")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("NhomHocTap");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.LoaiThongBao", "LoaiThongBao")
                        .WithMany("ThongBao")
                        .HasForeignKey("MaLoaiThongBao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("ThongBao")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiThongBao");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.ThongKeHocTap", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("ThongKeHocTap")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TinNhan", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.NguoiDung", "NguoiGui")
                        .WithMany("TinNhan")
                        .HasForeignKey("MaNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyHub.Domain.Entities.NhomHocTap", "NhomHocTap")
                        .WithMany("TinNhan")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NhomHocTap");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TinNhanAI", b =>
                {
                    b.HasOne("StudyHub.Domain.Entities.HoiThoaiAI", "HoiThoaiAI")
                        .WithMany("TinNhanAI")
                        .HasForeignKey("MaHoiThoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoiThoaiAI");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.CongViec", b =>
                {
                    b.Navigation("KanbanThe")
                        .IsRequired();

                    b.Navigation("PomodoroSession");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.FileTaiLen", b =>
                {
                    b.Navigation("LichSuTomTat");

                    b.Navigation("TaiLieu");

                    b.Navigation("TepDinhKemTinNhan");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.HoiThoaiAI", b =>
                {
                    b.Navigation("TinNhanAI");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanBoard", b =>
                {
                    b.Navigation("KanbanCot");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.KanbanCot", b =>
                {
                    b.Navigation("KanbanThe");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.LoaiThongBao", b =>
                {
                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.MonHoc", b =>
                {
                    b.Navigation("CongViec");

                    b.Navigation("LichHoc");

                    b.Navigation("LichThi");

                    b.Navigation("NhomHocTap");

                    b.Navigation("PomodoroSession");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("CongViec");

                    b.Navigation("FileTaiLen");

                    b.Navigation("HoiThoaiAI");

                    b.Navigation("KanbanBoard");

                    b.Navigation("LichHoc");

                    b.Navigation("LichSuQuiz");

                    b.Navigation("LichSuTomTat");

                    b.Navigation("LichThi");

                    b.Navigation("NhatKyHeThong");

                    b.Navigation("NhomCongViec");

                    b.Navigation("NhomHocTap");

                    b.Navigation("PhienDangNhap");

                    b.Navigation("PomodoroSession");

                    b.Navigation("SuKien");

                    b.Navigation("TaiLieu");

                    b.Navigation("ThanhVienNhom");

                    b.Navigation("ThongBao");

                    b.Navigation("ThongKeHocTap");

                    b.Navigation("TinNhan");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhomCongViec", b =>
                {
                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.NhomHocTap", b =>
                {
                    b.Navigation("TaiLieu");

                    b.Navigation("ThanhVienNhom");

                    b.Navigation("TinNhan");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.TinNhan", b =>
                {
                    b.Navigation("TepDinhKemTinNhan");
                });

            modelBuilder.Entity("StudyHub.Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
